// lib/bootstrap/firebase_boot.dart
import 'dart:io' show Platform;
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';
import '../firebase_options.dart'; // generated by `flutterfire configure`

/// One-shot Firebase initializer that NEVER relies on iOS plist auto-config.
/// We always pass [DefaultFirebaseOptions.currentPlatform].
class FirebaseBoot {
  FirebaseBoot._();
  static bool _started = false;

  static Future<void> ensure() async {
    if (_started) return;
    _started = true;

    try {
      // If already initialized (hot restart), bail out
      if (Firebase.apps.isNotEmpty) {
        if (kDebugMode) {
          debugPrint('[BOOT] Firebase already initialized: ${Firebase.apps.first.name}');
        }
        return;
      }

      final opts = DefaultFirebaseOptions.currentPlatform;
      await Firebase.initializeApp(name: 'default', options: opts);

      if (kDebugMode) {
        debugPrint('[BOOT] Firebase initialized with explicit options '
            '(platform=${Platform.isIOS ? "iOS" : Platform.operatingSystem})');
      }
    } on FirebaseException catch (e, st) {
      debugPrint('[BOOT] Firebase init failed: ${e.code} ${e.message}\n$st');
      rethrow;
    } catch (e, st) {
      debugPrint('[BOOT] Firebase init failed (non-Firebase): $e\n$st');
      rethrow;
    }
  }
}
