configurationName: Default Configuration
platformType: Flutter
platformSetting:
  projects:
  - type: Workspace
    path: ./ios/Runner.xcworkspace
    schemes:
    - name: Runner
      bundleIdentifier: 
      bundleIdentifiers:
      - com.fermentacraft
      extensions: []
  - type: Workspace
    path: ./macos/Runner.xcworkspace
    schemes:
    - name: Runner
      bundleIdentifier: 
      bundleIdentifiers: []
      extensions: []
  - type: Project
    path: ./ios/Runner.xcodeproj
    schemes:
    - name: Runner
      bundleIdentifier: 
      bundleIdentifiers:
      - com.fermentacraft
      extensions: []
  - type: Project
    path: ./macos/Runner.xcodeproj
    schemes:
    - name: Runner
      bundleIdentifier: 
      bundleIdentifiers: []
      extensions: []
  selectedXcodeVersion: 16.2.x
  selectedProject: ./ios/Runner.xcworkspace
  selectedScheme: Runner
  xcodeBuildExtraFlags: 
  exportOptionsPlist: 
  buildMode: Release
  buildExtraFlags: --no-codesign --verbose
  flutterVersion: 
  buildNumberSource: xcode
  iosBuildNumber: $AC_BUILD_NUMBER
  buildOffset: 1
  versionNumberSource: xcode
  iosVersionNumber: 
  versionStrategy: minor
  versionOffset: 1
  omitZeroPatchVersion: false
  bundleId: 
  appstoreCountry: 
  targets: []
  configurationName: 
  xcodeVersions:
  - 26.0.x
  - 16.4.x
  - 16.3.x
  - 16.2.x
  - 16.1.x
  - 16.0.x
  - 15.4.x
  - 15.3.x
  - 15.2.x
  - 15.1.x
  - 15.0.x
  - 14.3.x
  - 14.2.x
  - 14.1.x
  - 14.0.x
  - 13.4.x
  - 13.3.x
  - 13.2.x
  - 13.1.x
  - 13.0.x
  - 12.5.x
workflows: {}
autoBuild: 
runnerArchitecture: arm64
autoBuildTags: []
distributionProfileId: 
environmentVariables: 
signingIdentities:
- signingIdentityType: Certificate
  entityId: 371edb63-73ad-4eff-b34a-8a2ad73b8c28
  bundleIdentifier: 
- signingIdentityType: Certificate
  entityId: 6195a809-abd2-44cf-bb4c-30042d77c941
  bundleIdentifier: 
autoDistribute: false
autoPublish: false
autoStoreSubmit: false
autoAppGallerySubmit: false
autoEnterpriseStoreSend: false
autoSign: true
autoCancelRedundantPipelines: false
autoSignMethodForExport: development
autoSignApiKeyId: 45ad699f-9428-40aa-af28-e0df17921fa6
displayBuildStatusBadge: false
sendToSlack: false
slackChannel: 
organizationPoolId: 00000000-0000-0000-0000-000000000000
distributionProfileIds: 
publishProfileIds: 
buildPriority: Medium
