// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC05HjtZZ_e015sWqUcB3v92EGoHWgS2WI',
    appId: '1:747130944683:web:8a2db0e33d8acbed3b0bee',
    messagingSenderId: '747130944683',
    projectId: 'fermentacraft',
    authDomain: 'fermentacraft.firebaseapp.com',
    storageBucket: 'fermentacraft.firebasestorage.app',
    measurementId: 'G-DK0XDKH4KL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQrI2K1PSW1wBeo3SXoXuCp7BmIIW_0ok',
    appId: '1:747130944683:android:c8e4ec77afd61d483b0bee',
    messagingSenderId: '747130944683',
    projectId: 'fermentacraft',
    storageBucket: 'fermentacraft.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZe4o6R1DinoRCq5vaLIv7nGKy7PfvcgY',
    appId: '1:747130944683:ios:9e36933548b34a263b0bee',
    messagingSenderId: '747130944683',
    projectId: 'fermentacraft',
    storageBucket: 'fermentacraft.firebasestorage.app',
    androidClientId: '747130944683-70375t4voqs45f5t3tcb5n0ovtc7l25h.apps.googleusercontent.com',
    iosClientId: '747130944683-add6ufd63i82lh8ispnosi2ii3vu6hbn.apps.googleusercontent.com',
    iosBundleId: 'com.fermentacraft',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC05HjtZZ_e015sWqUcB3v92EGoHWgS2WI',
    appId: '1:747130944683:web:78884c5827e0c0793b0bee',
    messagingSenderId: '747130944683',
    projectId: 'fermentacraft',
    authDomain: 'fermentacraft.firebaseapp.com',
    storageBucket: 'fermentacraft.firebasestorage.app',
    measurementId: 'G-7P16BEM159',
  );

}